name: flutter_saltyrtc_client
description: The dart_saltyrtc_client integration in flutter, with support for iOS, Android and Web.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dart_saltyrtc_client:
    path: ../saltyrtc_client
  flutter_sodium: ^0.2.0
  libsodium: ^0.2.0
  web_socket_channel: ^2.1.0
  hex: ^0.2.0

dev_dependencies:
  logger: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.3
  equatable: ^2.0.3
