name: 'install_deps'
description: 'Install the dependencies for both projects'
runs:
 using: "composite"
 steps:
    - shell: bash
      name: Log flutter version
      run: flutter --version
    - shell: bash
      name: Install dart dependencies
      working-directory: saltyrtc_client
      run: flutter pub get

    - shell: bash
      name: Install flutter dependencies
      working-directory: flutter_saltyrtc_client
      run: flutter pub get

