name: dart_saltyrtc_client
description: The dart saltyrtc client.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  messagepack: 0.2.1
  meta: 1.7.0
  quiver: 3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
